# Workflow Types

WORKFLOW_CHEQUE = "cheque"
WORKFLOW_LOAN = "loan"
WORKFLOW_KYC = "kyc"
WORKFLOW_ONBOARDING = "onboarding"
WORKFLOW_CREDIT_CARD = "credit_card"
WORKFLOW_TRANSFER = "transfer"


# Workflow Status

STATUS_ACTIVE = "ACTIVE"
STATUS_WAITING = "WAITING"
STATUS_COMPLETED = "COMPLETED"
STATUS_FAILED = "FAILED"
STATUS_CANCELLED = "CANCELLED"


# Generic Steps

STEP_START = "START"
STEP_COMPLETED = "COMPLETED"


# Cheque Workflow

STEP_UPLOAD_CHEQUE = "UPLOAD_CHEQUE"
STEP_VALIDATE_CHEQUE = "VALIDATE_CHEQUE"
STEP_CORRECT_CHEQUE = "CORRECT_CHEQUE"
STEP_CREATE_CHEQUE_REQUEST = "CREATE_CHEQUE_REQUEST"


# Loan Workflow

STEP_UPLOAD_PAN = "UPLOAD_PAN"
STEP_UPLOAD_AADHAAR = "UPLOAD_AADHAAR"
STEP_UPLOAD_SALARY_SLIP = "UPLOAD_SALARY_SLIP"
STEP_UPLOAD_BANK_STATEMENT = "UPLOAD_BANK_STATEMENT"
STEP_UPLOAD_PROPERTY_DOCUMENT = "UPLOAD_PROPERTY_DOCUMENT"
STEP_VALIDATE_LOAN_DOCUMENTS = "VALIDATE_LOAN_DOCUMENTS"
STEP_CHECK_ELIGIBILITY = "CHECK_ELIGIBILITY"
STEP_CREATE_LOAN_REQUEST = "CREATE_LOAN_REQUEST"
STEP_SELECT_LOAN_TYPE = "SELECT_LOAN_TYPE"
STEP_UPLOAD_LOAN_FORM = "UPLOAD_LOAN_FORM"
STEP_CONFIRM_LOAN = "CONFIRM_LOAN"


# KYC Workflow

STEP_UPLOAD_KYC_DOCUMENT = "UPLOAD_KYC_DOCUMENT"
STEP_VALIDATE_KYC = "VALIDATE_KYC"
STEP_UPDATE_KYC = "UPDATE_KYC"
STEP_UPLOAD_KYC_FORM = "UPLOAD_KYC_FORM"
STEP_CONFIRM_KYC = "CONFIRM_KYC"


# Onboarding Workflow

STEP_UPLOAD_ID_PROOF = "UPLOAD_ID_PROOF"
STEP_UPLOAD_ADDRESS_PROOF = "UPLOAD_ADDRESS_PROOF"
STEP_VERIFY_CUSTOMER = "VERIFY_CUSTOMER"
STEP_CREATE_CUSTOMER = "CREATE_CUSTOMER"

STEP_COLLECT_AADHAAR = "COLLECT_AADHAAR"
STEP_COLLECT_PAN = "COLLECT_PAN"
STEP_CONFIRM_REGISTRATION = "CONFIRM_REGISTRATION"
STEP_SELECT_ACCOUNT_TYPE = "SELECT_ACCOUNT_TYPE"

# Transfer workflow
STEP_SELECT_BENEFICIARY = "SELECT_BENEFICIARY"
STEP_COLLECT_BENEFICIARY_NAME = "COLLECT_BENEFICIARY_NAME"
STEP_COLLECT_BENEFICIARY_ACCOUNT = "COLLECT_BENEFICIARY_ACCOUNT"
STEP_SELECT_AMOUNT = "SELECT_AMOUNT"
STEP_COLLECT_AMOUNT = "COLLECT_AMOUNT"
STEP_SELECT_SOURCE_ACCOUNT = "SELECT_SOURCE_ACCOUNT"
STEP_CONFIRM_TRANSFER = "CONFIRM_TRANSFER"
